=head1 NAME

calc.pl - Simple perl REPL calculator

=head1 SYNOPSIS

    $ calc.pl
    calc> 2 * pi * 32
    201.0619264
    calc> 

=head1 DESCRIPTION

Based upon the sample code from https://metacpan.org/pod/Term::ReadLine

To get readline working properly on OSX, I installed Term::ReadLine::GNU
following the instructions from
L<http://blogs.perl.org/users/aristotle/2013/07/easy-osx-termreadlinegnu.html>

Readline is already installed, but the Makefile doesn't pick it up, so make
homebrew instal some temporary symlinks.

    dave> brew install --force readline
    dave> sudo su -
    root> cpan Term::ReadLine::GNU
    root> exit
    dave> brew unlink readline


=cut

=head1 LICENSE

This script is free software; you can redistribute it and/or modify it under
the same terms as perl itself.


=cut

